package oops;

public class SuperConstructorsDemo3 extends ParentDemo{
	//default constructor generated by compiler
	/*SuperConstructorsDemo3(){
		super();
	}*/
	public static void main(String[] args) {
		new SuperConstructorsDemo3();
	}

}
