package oops;

public class SuperConstructorDemo4 extends Object{
	SuperConstructorDemo4(){
		//super(); generated by compiler
		System.out.println("Current class 0-arg constructor");
	}
	public static void main(String[] args) {
		new SuperConstructorDemo4();
	}

}
